In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [23]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [35]:
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [4]:
df = pd.read_csv("16-diabetes.csv")

In [5]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [6]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [8]:
df.describe()

ERROR! Session/line number was not unique in database. History logging moved to new session 2

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [9]:
df["Insulin"].value_counts()

Insulin
0      374
105     11
140      9
130      9
120      8
      ...
178      1
127      1
510      1
16       1
112      1
Name: count, Length: 186, dtype: int64

In [10]:
df.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='str')

In [14]:
columns_to_check = ["Glucose","BloodPressure","SkinThickness","Insulin","BMI"]

for col in columns_to_check:
    zero_count = (df[col] == 0).sum()
    zero_percentage = 100 * zero_count / len(df)
    print(f"{col}: {zero_count}  %{zero_percentage:.2f}")

Glucose: 5  %0.65
BloodPressure: 35  %4.56
SkinThickness: 227  %29.56
Insulin: 374  %48.70
BMI: 11  %1.43

In [15]:
X = df.drop("Outcome",axis=1)
y = df["Outcome"]

In [16]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=15)

In [17]:
columns_to_fill = ["Glucose","BloodPressure","SkinThickness","Insulin","BMI"]

In [18]:
medians = {}
for col in columns_to_fill:
    median_value = X_train[X_train[col] != 0][col].median()
    medians[col] = median_value
    X_train[col] = X_train[col].replace(0, median_value)

for col in columns_to_fill:
    X_test[col] = X_test[col].replace(0, medians[col])

In [20]:
X_train.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
count,614.000000,614.000000,614.000000,614.000000,614.000000,614.000000,614.000000,614.000000
mean,3.907166,121.560261,72.612378,29.040717,142.477199,32.448208,0.469948,33.285016
std,3.385438,29.974412,12.165642,8.312217,80.879330,6.862948,0.328516,11.678337
min,0.000000,44.000000,24.000000,7.000000,14.000000,18.200000,0.084000,21.000000
25%,1.000000,100.000000,64.000000,25.000000,125.000000,27.600000,0.238250,24.000000
50%,3.000000,117.000000,72.000000,29.000000,129.500000,32.300000,0.370500,29.000000
75%,6.000000,139.750000,80.000000,32.000000,130.000000,36.500000,0.630750,40.000000
max,17.000000,199.000000,122.000000,63.000000,680.000000,67.100000,2.420000,81.000000

In [22]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [24]:
ada = AdaBoostClassifier()
ada.fit(X_train,y_train)
y_pred = ada.predict(X_test)

In [25]:
print(classification_report(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.84      0.81      0.82       108
           1       0.58      0.63      0.60        46

    accuracy                           0.75       154
   macro avg       0.71      0.72      0.71       154
weighted avg       0.76      0.75      0.76       154

0.7532467532467533
[[87 21]
 [17 29]]

In [26]:
#hyperparameter tuning

In [27]:
from sklearn.model_selection import GridSearchCV

In [28]:
adaboost_param = {
    "n_estimators" : [50,70,100,120,150,200],
    "learning_rate" : [0.001,0.01,0.1,1,10]
}

In [30]:
grid = GridSearchCV(estimator=AdaBoostClassifier(),param_grid=adaboost_param,cv=3,verbose=1,n_jobs=-1)
grid.fit(X_train,y_train)

Fitting 3 folds for each of 30 candidates, totalling 90 fits

GridSearchCV(cv=3, estimator=AdaBoostClassifier(), n_jobs=-1,
             param_grid={'learning_rate': [0.001, 0.01, 0.1, 1, 10],
                         'n_estimators': [50, 70, 100, 120, 150, 200]},
             verbose=1)

In [31]:
grid.best_params_

{'learning_rate': 1, 'n_estimators': 200}

In [33]:
ada = AdaBoostClassifier(n_estimators=200,learning_rate=1)
ada.fit(X_train,y_train)
y_pred = ada.predict(X_test)
print(classification_report(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.83      0.80      0.82       108
           1       0.57      0.63      0.60        46

    accuracy                           0.75       154
   macro avg       0.70      0.71      0.71       154
weighted avg       0.76      0.75      0.75       154

0.7467532467532467
[[86 22]
 [17 29]]

In [36]:
def calculate_model_metrics(true,predicted):
    class_report = classification_report(true,predicted)
    conf_matrix = confusion_matrix(true,predicted)
    score = accuracy_score(true,predicted)
    return class_report,conf_matrix,score

In [37]:
models = {
    "Logistic Regression" : LogisticRegression(),
    "Naive Bayes" : GaussianNB(),
    "KNN Classifier" : KNeighborsClassifier(),
    "SVC" : SVC(),
    "Decision Tree Classifier" : DecisionTreeClassifier(),
    "Random Forest Classifier" : RandomForestClassifier()
}

In [38]:
for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train,y_train)
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    model_train_class_rep , model_train_confusion,  model_train_score = calculate_model_metrics(y_train,y_train_pred)
    model_test_class_rep , model_test_confusion,  model_test_score = calculate_model_metrics(y_test,y_test_pred)

    print(list(models.values())[i])
    print("Evalution for Training Set")
    print("Classification Report :", model_train_class_rep)
    print("Confusion Matrix :",model_train_confusion)
    print("Accuracy Score :",model_train_score)

    print("------------------------")
    print(list(models.values())[i])
    print("Evalution for Test Set")
    print("Classification Report :", model_test_class_rep)
    print("Confusion Matrix :",model_test_confusion)
    print("Accuracy Score :",model_test_score)

    print("------------------------")
    print("\n")

LogisticRegression()
Evalution for Training Set
Classification Report :               precision    recall  f1-score   support

           0       0.80      0.89      0.84       392
           1       0.75      0.60      0.67       222

    accuracy                           0.78       614
   macro avg       0.77      0.74      0.75       614
weighted avg       0.78      0.78      0.78       614

Confusion Matrix : [[347  45]
 [ 88 134]]
Accuracy Score : 0.7833876221498371
------------------------
LogisticRegression()
Evalution for Test Set
Classification Report :               precision    recall  f1-score   support

           0       0.82      0.82      0.82       108
           1       0.59      0.59      0.59        46

    accuracy                           0.75       154
   macro avg       0.71      0.71      0.71       154
weighted avg       0.75      0.75      0.75       154

Confusion Matrix : [[89 19]
 [19 27]]
Accuracy Score : 0.7532467532467533
------------------------


GaussianNB()
Evalution for Training Set
Classification Report :               precision    recall  f1-score   support

           0       0.80      0.84      0.82       392
           1       0.69      0.64      0.66       222

    accuracy                           0.77       614
   macro avg       0.75      0.74      0.74       614
weighted avg       0.76      0.77      0.76       614

Confusion Matrix : [[329  63]
 [ 81 141]]
Accuracy Score : 0.7654723127035831
------------------------
GaussianNB()
Evalution for Test Set
Classification Report :               precision    recall  f1-score   support

           0       0.81      0.79      0.80       108
           1       0.53      0.57      0.55        46

    accuracy                           0.72       154
   macro avg       0.67      0.68      0.67       154
weighted avg       0.73      0.72      0.72       154

Confusion Matrix : [[85 23]
 [20 26]]
Accuracy Score : 0.7207792207792207
------------------------


KNeighborsClassifier()
Evalution for Training Set
Classification Report :               precision    recall  f1-score   support

           0       0.86      0.88      0.87       392
           1       0.78      0.74      0.76       222

    accuracy                           0.83       614
   macro avg       0.82      0.81      0.81       614
weighted avg       0.83      0.83      0.83       614

Confusion Matrix : [[346  46]
 [ 58 164]]
Accuracy Score : 0.8306188925081434
------------------------
KNeighborsClassifier()
Evalution for Test Set
Classification Report :               precision    recall  f1-score   support

           0       0.80      0.75      0.78       108
           1       0.49      0.57      0.53        46

    accuracy                           0.69       154
   macro avg       0.65      0.66      0.65       154
weighted avg       0.71      0.69      0.70       154

Confusion Matrix : [[81 27]
 [20 26]]
Accuracy Score : 0.6948051948051948
------------------------


SVC()
Evalution for Training Set
Classification Report :               precision    recall  f1-score   support

           0       0.84      0.92      0.88       392
           1       0.84      0.69      0.76       222

    accuracy                           0.84       614
   macro avg       0.84      0.81      0.82       614
weighted avg       0.84      0.84      0.83       614

Confusion Matrix : [[362  30]
 [ 69 153]]
Accuracy Score : 0.8387622149837134
------------------------
SVC()
Evalution for Test Set
Classification Report :               precision    recall  f1-score   support

           0       0.81      0.81      0.81       108
           1       0.54      0.54      0.54        46

    accuracy                           0.73       154
   macro avg       0.67      0.67      0.67       154
weighted avg       0.73      0.73      0.73       154

Confusion Matrix : [[87 21]
 [21 25]]
Accuracy Score : 0.7272727272727273
------------------------


DecisionTreeClassifier()
Evalution for Training Set
Classification Report :               precision    recall  f1-score   support

           0       1.00      1.00      1.00       392
           1       1.00      1.00      1.00       222

    accuracy                           1.00       614
   macro avg       1.00      1.00      1.00       614
weighted avg       1.00      1.00      1.00       614

Confusion Matrix : [[392   0]
 [  0 222]]
Accuracy Score : 1.0
------------------------
DecisionTreeClassifier()
Evalution for Test Set
Classification Report :               precision    recall  f1-score   support

           0       0.81      0.72      0.76       108
           1       0.48      0.61      0.54        46

    accuracy                           0.69       154
   macro avg       0.65      0.67      0.65       154
weighted avg       0.71      0.69      0.70       154

Confusion Matrix : [[78 30]
 [18 28]]
Accuracy Score : 0.6883116883116883
------------------------


RandomForestClassifier()
Evalution for Training Set
Classification Report :               precision    recall  f1-score   support

           0       1.00      1.00      1.00       392
           1       1.00      1.00      1.00       222

    accuracy                           1.00       614
   macro avg       1.00      1.00      1.00       614
weighted avg       1.00      1.00      1.00       614

Confusion Matrix : [[392   0]
 [  0 222]]
Accuracy Score : 1.0
------------------------
RandomForestClassifier()
Evalution for Test Set
Classification Report :               precision    recall  f1-score   support

           0       0.82      0.78      0.80       108
           1       0.53      0.59      0.56        46

    accuracy                           0.72       154
   macro avg       0.67      0.68      0.68       154
weighted avg       0.73      0.72      0.72       154

Confusion Matrix : [[84 24]
 [19 27]]
Accuracy Score : 0.7207792207792207
------------------------